services:
  db:
    image: postgres:latest
    container_name: biere_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - dockerbeer:/var/lib/postgresql/data/
      - ./db-scripts:/docker-entrypoint-initdb.d/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myAPIREST_zythlogie_AM
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
    - .:/usr/src/biere-api
    depends_on:
      - db

volumes:
  dockerbeer: